name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-cgpa-calculator:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: change directory
      run: |
        cd beginner/cgpa_calculator
        cmake .
        make


  build-rock-paper-scissor:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build
      run: |
        cd beginner/rock_paper_scissor
        cmake .
        make


  build-beginner-cassino-number-guessing:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: change directory
      run: |
        cd beginner/cassino_number_guessing
        cmake .
        make


  # build-login-and-registration-system:

  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: change directory
  #     run: |
        # cd beginner/login_and_registration_system
        # cmake .
        # make
